name: Discord Bot
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 4,8,12,16,20 * * *"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checking out repository content
        uses: actions/checkout@v2

      - name: Setting up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Extract contents
        run: |
            extractor e "rave.7z" -p"${{ secrets.ARCHIVE_PASSWORD }}" -spf
      
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Bot code
        run: |
          python me.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
